const products = [
	{
		_id: 1,
		name: "Product A",
		image: "https://i.imgur.com/Q4mX7Mv.jpg",
		description: "DJ Quik",
		brand: "Sony",
		category: "Music",
		price: 99.99,
		countInStock: "3",
		rating: 2.5,
		numReviews: 4,
	},
	{
		_id: 2,
		name: "Product A",
		image: "https://i.imgur.com/HpcI73e.jpg",
		description: "DJ Quik",
		brand: "Sony",
		category: "Music",
		price: 99.99,
		countInStock: "3",
		rating: 2.5,
		numReviews: 4,
	},
	{
		_id: 3,
		name: "Product A",
		image: "https://i.imgur.com/eZxCAq6.png",
		description: "DJ Quik",
		brand: "Sony",
		category: "Music",
		price: 99.99,
		countInStock: "3",
		rating: 4.5,
		numReviews: 4,
	},
	{
		_id: 4,
		name: "Product A",
		image: "https://i.imgur.com/Jh44CXU.jpg",
		description: "DJ Quik",
		brand: "Sony",
		category: "Music",
		price: 99.99,
		countInStock: "3",
		rating: 4.5,
		numReviews: 4,
	},
];

export default products;
